# Generated by Django 5.0.3 on 2024-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_body',
        ),
        migrations.AlterField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(upload_to='audio_messages/'),
        ),
    ]
