# Generated by Django 5.0.3 on 2024-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_encrypted_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='audio_file',
            field=models.FileField(upload_to='audio_messages'),
        ),
    ]
