# Generated by Django 5.0.3 on 2024-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_audiomessage_audio_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioMessage',
        ),
    ]
