# Generated by Django 5.0.3 on 2024-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='photo_files/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
